// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {
    ActionButtonDetail,
    ActionButtonPreview,
    ButtonDetail,
    ButtonPreview,
    IconButtonDetail,
    IconButtonPreview,
} from './specimens/actions';
import {
    GlobalBannerDetail,
    GlobalBannerPreview,
    MoreUnreadsBannerDetail,
    MoreUnreadsBannerPreview,
    NewMessageBannerDetail,
    NewMessageBannerPreview,
    SearchTipBannerDetail,
    SearchTipBannerPreview,
} from './specimens/banners';
import {
    AttachmentCardDetail,
    AttachmentCardPreview,
    ImagePreviewDetail,
    ImagePreviewPreview,
    LinkPreviewDetail,
    LinkPreviewPreview,
    PermalinkPreviewDetail,
    PermalinkPreviewPreview,
} from './specimens/cards';
import {
    AdminConsoleHeaderDetail,
    AdminConsoleHeaderPreview,
    FeatureDiscoveryPanelDetail,
    FeatureDiscoveryPanelPreview,
    GlobalHeaderDetail,
    GlobalHeaderPreview,
    RightSidebarHeaderDetail,
    RightSidebarHeaderPreview,
    TeamSidebarDetail,
    TeamSidebarPreview,
} from './specimens/chrome';
import {
    ErrorMessageDetail,
    ErrorMessagePreview,
    PopoverNoticeDetail,
    PopoverNoticePreview,
    SectionNoticeDetail,
    SectionNoticePreview,
    ToastDetail,
    ToastPreview,
    TooltipDetail,
    TooltipPreview,
} from './specimens/feedback';
import {
    CheckboxDetail,
    CheckboxPreview,
    ChipDetail,
    ChipPreview,
    ComboboxDetail,
    ComboboxPreview,
    DateRangePickerDetail,
    DateRangePickerPreview,
    DropdownDetail,
    DropdownPreview,
    RadioDetail,
    RadioPreview,
    SearchInputDetail,
    SearchInputPreview,
    SelectDetail,
    SelectPreview,
    SwitchDetail,
    SwitchPreview,
    TextAreaDetail,
    TextAreaPreview,
    TextInputDetail,
    TextInputPreview,
} from './specimens/forms';
import {
    EmojiDetail,
    EmojiPreview,
    IconDetail,
    IconPreview,
    IllustrationDetail,
    IllustrationPreview,
    TeamAvatarDetail,
    TeamAvatarPreview,
    UserAvatarDetail,
    UserAvatarPreview,
    UserAvatarGroupDetail,
    UserAvatarGroupPreview,
} from './specimens/images';
import {
    DividerDetail,
    DividerPreview,
    EmptyStateDetail,
    EmptyStatePreview,
    ScrollbarDetail,
    ScrollbarPreview,
    TabsDetail,
    TabsPreview,
} from './specimens/layout';
import {
    MessageHeaderDetail,
    MessageHeaderPreview,
    MessageSeparatorDetail,
    MessageSeparatorPreview,
    ThreadFooterDetail,
    ThreadFooterPreview,
    ThreadListItemDetail,
    ThreadListItemPreview,
} from './specimens/messaging';
import {
    ChannelSidebarItemDetail,
    ChannelSidebarItemPreview,
    MenuItemDetail,
    MenuItemPreview,
} from './specimens/navigation';
import {
    ModalDetail,
    ModalPreview,
    PopoverMenuDetail,
    PopoverMenuPreview,
    ProfilePopoverDetail,
    ProfilePopoverPreview,
    TourPointDetail,
    TourPointPreview,
} from './specimens/patterns';
import {
    PaginationDotsDetail,
    PaginationDotsPreview,
    ProgressBarDetail,
    ProgressBarPreview,
    SpinnerDetail,
    SpinnerPreview,
} from './specimens/progress';
import {
    MentionBadgeDetail,
    MentionBadgePreview,
    ShortcutTagDetail,
    ShortcutTagPreview,
    StatusBadgeDetail,
    StatusBadgePreview,
    TagDetail,
    TagPreview,
    UnreadBadgeDetail,
    UnreadBadgePreview,
} from './specimens/status';
import type {CatalogEntry} from './types';

export const CATALOG: CatalogEntry[] = [
    {
        id: 'button',
        name: 'Button',
        category: 'actions',
        description: 'Primary actions for forms, dialogs, and confirmations.',
        preview: ButtonPreview,
        detail: ButtonDetail,
    },
    {
        id: 'icon-button',
        name: 'Icon Button',
        category: 'actions',
        description: 'Compact, label-free actions for headers and toolbars.',
        preview: IconButtonPreview,
        detail: IconButtonDetail,
    },
    {
        id: 'action-button',
        name: 'Action Button',
        category: 'actions',
        description: 'Equal-weight choices next to the content they act on.',
        preview: ActionButtonPreview,
        detail: ActionButtonDetail,
    },
    {
        id: 'search-input',
        name: 'Search Input',
        category: 'forms',
        description: 'Filter or find content with a leading magnifier.',
        preview: SearchInputPreview,
        detail: SearchInputDetail,
    },
    {
        id: 'text-input',
        name: 'Text Input',
        category: 'forms',
        description: 'Single-line text for names, URLs, and titles.',
        preview: TextInputPreview,
        detail: TextInputDetail,
    },
    {
        id: 'text-area',
        name: 'Text Area',
        category: 'forms',
        description: 'Multi-line text for descriptions and notes.',
        preview: TextAreaPreview,
        detail: TextAreaDetail,
    },
    {
        id: 'checkbox',
        name: 'Checkbox',
        category: 'forms',
        description: 'Independent on/off choices in a form.',
        preview: CheckboxPreview,
        detail: CheckboxDetail,
    },
    {
        id: 'radio',
        name: 'Radio',
        category: 'forms',
        description: 'Pick exactly one option from a small set.',
        preview: RadioPreview,
        detail: RadioDetail,
    },
    {
        id: 'switch',
        name: 'Switch',
        category: 'forms',
        description: 'Immediate binary settings that take effect on flip.',
        preview: SwitchPreview,
        detail: SwitchDetail,
    },
    {
        id: 'select',
        name: 'Select',
        category: 'forms',
        description: 'Choose one value from a list of options.',
        preview: SelectPreview,
        detail: SelectDetail,
    },
    {
        id: 'chip',
        name: 'Chip',
        category: 'forms',
        description: 'Compact tokens for selected people, tags, or filters.',
        preview: ChipPreview,
        detail: ChipDetail,
    },
    {
        id: 'combobox',
        name: 'Combobox',
        category: 'forms',
        description: 'Search and select one or many values.',
        preview: ComboboxPreview,
        detail: ComboboxDetail,
    },
    {
        id: 'dropdown',
        name: 'Dropdown',
        category: 'forms',
        description: 'Trigger for a menu of choices.',
        preview: DropdownPreview,
        detail: DropdownDetail,
    },
    {
        id: 'date-range-picker',
        name: 'Date Range Picker',
        category: 'forms',
        description: 'Pick a single date or a start and end date.',
        preview: DateRangePickerPreview,
        detail: DateRangePickerDetail,
    },
    {
        id: 'error-message',
        name: 'Error Message',
        category: 'feedback',
        description: 'Inline validation copy beneath a field.',
        preview: ErrorMessagePreview,
        detail: ErrorMessageDetail,
    },
    {
        id: 'section-notice',
        name: 'Section Notice',
        category: 'feedback',
        description: 'In-page notice with optional actions.',
        preview: SectionNoticePreview,
        detail: SectionNoticeDetail,
    },
    {
        id: 'toast',
        name: 'Toast',
        category: 'feedback',
        description: 'Transient confirmation that an action completed.',
        preview: ToastPreview,
        detail: ToastDetail,
    },
    {
        id: 'tooltip',
        name: 'Tooltip',
        category: 'feedback',
        description: 'Short supporting text. Chrome only — host owns hover.',
        preview: TooltipPreview,
        detail: TooltipDetail,
    },
    {
        id: 'popover-notice',
        name: 'Popover Notice',
        category: 'feedback',
        description: 'A small teaching or confirmation popover.',
        preview: PopoverNoticePreview,
        detail: PopoverNoticeDetail,
    },
    {
        id: 'icon',
        name: 'Icon',
        category: 'images',
        description: 'Sized wrapper for compass-icons glyphs.',
        preview: IconPreview,
        detail: IconDetail,
    },
    {
        id: 'emoji',
        name: 'Emoji',
        category: 'images',
        description: 'Emoji at the Mattermost icon scale.',
        preview: EmojiPreview,
        detail: EmojiDetail,
    },
    {
        id: 'user-avatar',
        name: 'User Avatar',
        category: 'images',
        description: 'Photo or initials for a person, with optional status.',
        preview: UserAvatarPreview,
        detail: UserAvatarDetail,
    },
    {
        id: 'user-avatar-group',
        name: 'User Avatar Group',
        category: 'images',
        description: 'Stacked avatars with an overflow count.',
        preview: UserAvatarGroupPreview,
        detail: UserAvatarGroupDetail,
    },
    {
        id: 'team-avatar',
        name: 'Team Avatar',
        category: 'images',
        description: 'Rounded-square identity for a team.',
        preview: TeamAvatarPreview,
        detail: TeamAvatarDetail,
        previewSurface: 'sidebar',
    },
    {
        id: 'illustration',
        name: 'Illustration',
        category: 'images',
        description: 'Sized wrapper for brand SVG artwork.',
        preview: IllustrationPreview,
        detail: IllustrationDetail,
    },
    {
        id: 'divider',
        name: 'Divider',
        category: 'layout',
        description: 'A thin rule that separates related groups.',
        preview: DividerPreview,
        detail: DividerDetail,
    },
    {
        id: 'empty-state',
        name: 'Empty State',
        category: 'layout',
        description: 'Placeholder for a view with no content yet.',
        preview: EmptyStatePreview,
        detail: EmptyStateDetail,
    },
    {
        id: 'scrollbar',
        name: 'Scrollbar',
        category: 'layout',
        description: 'Minimal thumb for overflowing regions.',
        preview: ScrollbarPreview,
        detail: ScrollbarDetail,
    },
    {
        id: 'tabs',
        name: 'Tabs',
        category: 'layout',
        description: 'Switch sibling views or filter a list.',
        preview: TabsPreview,
        detail: TabsDetail,
    },
    {
        id: 'spinner',
        name: 'Spinner',
        category: 'progress',
        description: 'Indeterminate wait indicator.',
        preview: SpinnerPreview,
        detail: SpinnerDetail,
    },
    {
        id: 'progress-bar',
        name: 'Progress Bar',
        category: 'progress',
        description: 'Determinate progress when the total is known.',
        preview: ProgressBarPreview,
        detail: ProgressBarDetail,
    },
    {
        id: 'pagination-dots',
        name: 'Pagination Dots',
        category: 'progress',
        description: 'Step indicator for a fixed sequence.',
        preview: PaginationDotsPreview,
        detail: PaginationDotsDetail,
    },
    {
        id: 'tag',
        name: 'Tag',
        category: 'status',
        description: 'Compact pill for a role, tier, or state.',
        preview: TagPreview,
        detail: TagDetail,
    },
    {
        id: 'shortcut-tag',
        name: 'Shortcut Tag',
        category: 'status',
        description: 'Keyboard key chips for menus and tooltips.',
        preview: ShortcutTagPreview,
        detail: ShortcutTagDetail,
    },
    {
        id: 'mention-badge',
        name: 'Mention Badge',
        category: 'status',
        description: 'Numeric count of pending mentions.',
        preview: MentionBadgePreview,
        detail: MentionBadgeDetail,
    },
    {
        id: 'status-badge',
        name: 'Status Badge',
        category: 'status',
        description: 'Online, away, DND, or offline presence.',
        preview: StatusBadgePreview,
        detail: StatusBadgeDetail,
    },
    {
        id: 'unread-badge',
        name: 'Unread Badge',
        category: 'status',
        description: 'A small dot when a count would be noisy.',
        preview: UnreadBadgePreview,
        detail: UnreadBadgeDetail,
    },
    {
        id: 'attachment-card',
        name: 'Attachment Card',
        category: 'cards',
        description: 'File row with type icon and metadata.',
        preview: AttachmentCardPreview,
        detail: AttachmentCardDetail,
    },
    {
        id: 'image-preview',
        name: 'Image Preview',
        category: 'cards',
        description: 'Framed image attachment in the message stream.',
        preview: ImagePreviewPreview,
        detail: ImagePreviewDetail,
    },
    {
        id: 'link-preview',
        name: 'Link Preview',
        category: 'cards',
        description: 'Unfurled link with title and description.',
        preview: LinkPreviewPreview,
        detail: LinkPreviewDetail,
    },
    {
        id: 'permalink-preview',
        name: 'Permalink Preview',
        category: 'cards',
        description: 'Quoted message card for a permalink.',
        preview: PermalinkPreviewPreview,
        detail: PermalinkPreviewDetail,
    },
    {
        id: 'message-header',
        name: 'Message Header',
        category: 'messaging',
        description: 'Username, optional bot tag, and timestamp.',
        preview: MessageHeaderPreview,
        detail: MessageHeaderDetail,
    },
    {
        id: 'message-separator',
        name: 'Message Separator',
        category: 'messaging',
        description: 'Date, new-messages, or reply-count divider.',
        preview: MessageSeparatorPreview,
        detail: MessageSeparatorDetail,
    },
    {
        id: 'thread-footer',
        name: 'Thread Footer',
        category: 'messaging',
        description: 'Reply summary under a root message.',
        preview: ThreadFooterPreview,
        detail: ThreadFooterDetail,
    },
    {
        id: 'thread-list-item',
        name: 'Thread List Item',
        category: 'messaging',
        description: 'A single row in the Threads view.',
        preview: ThreadListItemPreview,
        detail: ThreadListItemDetail,
    },
    {
        id: 'menu-item',
        name: 'Menu Item',
        category: 'navigation',
        description: 'Selectable row inside a menu.',
        preview: MenuItemPreview,
        detail: MenuItemDetail,
    },
    {
        id: 'channel-sidebar-item',
        name: 'Channel Sidebar Item',
        category: 'navigation',
        description: 'Channel or DM row in the left sidebar.',
        preview: ChannelSidebarItemPreview,
        detail: ChannelSidebarItemDetail,
    },
    {
        id: 'modal',
        name: 'Modal',
        category: 'patterns',
        description: 'Dialog chrome. Host owns portal and focus trap.',
        preview: ModalPreview,
        detail: ModalDetail,
    },
    {
        id: 'popover-menu',
        name: 'Popover Menu',
        category: 'patterns',
        description: 'Elevated surface for menu rows.',
        preview: PopoverMenuPreview,
        detail: PopoverMenuDetail,
    },
    {
        id: 'profile-popover',
        name: 'Profile Popover',
        category: 'patterns',
        description: 'User card chrome. Host owns open and positioning.',
        preview: ProfilePopoverPreview,
        detail: ProfilePopoverDetail,
    },
    {
        id: 'tour-point',
        name: 'Tour Point',
        category: 'patterns',
        description: 'Onboarding callout with optional progress dots.',
        preview: TourPointPreview,
        detail: TourPointDetail,
    },
    {
        id: 'global-banner',
        name: 'Global Banner',
        category: 'banners',
        description: 'Workspace-wide message at the top of the app.',
        preview: GlobalBannerPreview,
        detail: GlobalBannerDetail,
    },
    {
        id: 'more-unreads-banner',
        name: 'More Unreads Banner',
        category: 'banners',
        description: 'Pill that jumps to unread channels out of view.',
        preview: MoreUnreadsBannerPreview,
        detail: MoreUnreadsBannerDetail,
    },
    {
        id: 'new-message-banner',
        name: 'New Message Banner',
        category: 'banners',
        description: 'Jump to unreads in the channel you are reading.',
        preview: NewMessageBannerPreview,
        detail: NewMessageBannerDetail,
    },
    {
        id: 'search-tip-banner',
        name: 'Search Tip Banner',
        category: 'banners',
        description: 'Nudge toward the in-channel search shortcut.',
        preview: SearchTipBannerPreview,
        detail: SearchTipBannerDetail,
    },
    {
        id: 'global-header',
        name: 'Global Header',
        category: 'chrome',
        description: 'App header excerpt — too wide for a full RHS layout.',
        preview: GlobalHeaderPreview,
        detail: GlobalHeaderDetail,
    },
    {
        id: 'team-sidebar',
        name: 'Team Sidebar',
        category: 'chrome',
        description: 'Team switcher strip with unread and mention badges.',
        preview: TeamSidebarPreview,
        detail: TeamSidebarDetail,
    },
    {
        id: 'right-sidebar-header',
        name: 'Right Sidebar Header',
        category: 'chrome',
        description: 'RHS title row excerpt. This plugin does not wrap with Compass RHS chrome.',
        preview: RightSidebarHeaderPreview,
        detail: RightSidebarHeaderDetail,
    },
    {
        id: 'admin-console-header',
        name: 'Admin Console Header',
        category: 'chrome',
        description: 'System Console page title stripe.',
        preview: AdminConsoleHeaderPreview,
        detail: AdminConsoleHeaderDetail,
    },
    {
        id: 'feature-discovery-panel',
        name: 'Feature Discovery Panel',
        category: 'chrome',
        description: 'Higher-SKU feature pitch for System Console admins.',
        preview: FeatureDiscoveryPanelPreview,
        detail: FeatureDiscoveryPanelDetail,
    },
];
